//! Owns only subtitles generated by this application, never user media or subtitle files.
use serde::{Deserialize, Serialize};
use std::{fs::OpenOptions, io::Write, path::PathBuf};

pub(super) const MAX_ASS_BYTES: usize = 8 * 1024 * 1024;

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DanmakuRequest {
    pub session_id: String,
    pub revision: u64,
    pub ass_content: Option<String>,
    pub visible: bool,
}

#[derive(Clone, Debug, Serialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DanmakuResult {
    pub revision: u64,
    pub state: &'static str,
}

pub(super) trait SubtitleBackend {
    fn command(&self, args: &[&str]) -> Result<(), String>;
    fn selected_subtitle(&self) -> String;
    fn track_for_file(&self, path: &str) -> Option<i64>;
    fn media_ready(&self) -> bool;
}

struct OwnedAss(PathBuf);
impl OwnedAss {
    fn write(content: &str) -> Result<Self, String> {
        let mut random = [0u8; 16];
        getrandom::fill(&mut random).map_err(|error| error.to_string())?;
        let name = random
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        let path =
            std::env::temp_dir().join(format!("danmaku-preview-{}-{name}.ass", std::process::id()));
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&path)
            .map_err(|error| format!("无法创建弹幕预览文件：{error}"))?;
        let owned = Self(path);
        file.write_all(content.as_bytes())
            .map_err(|error| format!("无法写入弹幕预览：{error}"))?;
        Ok(owned)
    }
    fn name(&self) -> String {
        self.0.to_string_lossy().into_owned()
    }
}
impl Drop for OwnedAss {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.0);
    }
}

#[derive(Default)]
pub(super) struct SubtitleTrack {
    desired: Option<DanmakuRequest>,
    applied_revision: Option<u64>,
    file: Option<OwnedAss>,
    track_id: Option<i64>,
    previous_sid: Option<String>,
}

pub(super) fn validate(request: &DanmakuRequest) -> Result<(), String> {
    if request.revision > 9_007_199_254_740_991 {
        return Err("弹幕轨版本必须是安全整数。".into());
    }
    if let Some(content) = &request.ass_content {
        if content.len() > MAX_ASS_BYTES || content.contains('\0') {
            return Err("弹幕 ASS 超过 8 MiB 或包含非法空字符。".into());
        }
        if !content.contains("[Script Info]") || !content.contains("[Events]") {
            return Err("弹幕预览缺少有效的 ASS 头和事件区。".into());
        }
    }
    Ok(())
}

impl SubtitleTrack {
    pub fn set(
        &mut self,
        request: DanmakuRequest,
        backend: &impl SubtitleBackend,
    ) -> Result<DanmakuResult, String> {
        validate(&request)?;
        if self
            .desired
            .as_ref()
            .is_none_or(|current| request.revision > current.revision)
        {
            self.remove_owned(backend)?;
            self.applied_revision = None;
            self.desired = Some(request);
        }
        self.flush(backend)
    }

    pub fn flush(&mut self, backend: &impl SubtitleBackend) -> Result<DanmakuResult, String> {
        let Some(request) = self.desired.as_ref() else {
            return Ok(DanmakuResult {
                revision: 0,
                state: "cleared",
            });
        };
        let revision = request.revision;
        let Some(content) = request.ass_content.as_deref() else {
            self.applied_revision = Some(revision);
            return Ok(DanmakuResult {
                revision,
                state: "cleared",
            });
        };
        if self.applied_revision == Some(revision) {
            return Ok(DanmakuResult {
                revision,
                state: "applied",
            });
        }
        if !backend.media_ready() {
            return Ok(DanmakuResult {
                revision,
                state: "pending",
            });
        }
        if self.file.is_none() {
            let file = OwnedAss::write(content)?;
            self.previous_sid = Some(backend.selected_subtitle());
            backend.command(&["sub-add", &file.name(), "auto", "Danmaku Studio preview"])?;
            self.file = Some(file);
        }
        let file_name = self.file.as_ref().unwrap().name();
        let Some(id) = backend.track_for_file(&file_name) else {
            return Ok(DanmakuResult {
                revision,
                state: "pending",
            });
        };
        self.track_id = Some(id);
        if request.visible {
            // During preview the generated ASS is primary, preserving all motion/style tags.
            // Clearing/hiding restores the movie's previous subtitle selection.
            backend.command(&["set", "sid", &id.to_string()])?;
        }
        self.applied_revision = Some(revision);
        Ok(DanmakuResult {
            revision,
            state: "applied",
        })
    }

    pub fn clear_for_media_change(&mut self, backend: &impl SubtitleBackend) -> Result<(), String> {
        self.remove_owned(backend)?;
        self.desired = None;
        self.applied_revision = None;
        Ok(())
    }

    fn remove_owned(&mut self, backend: &impl SubtitleBackend) -> Result<(), String> {
        let id = self.track_id.or_else(|| {
            self.file
                .as_ref()
                .and_then(|file| backend.track_for_file(&file.name()))
        });
        if let Some(id) = id {
            let restore = backend.selected_subtitle() == id.to_string();
            backend.command(&["sub-remove", &id.to_string()])?;
            if restore {
                backend.command(&["set", "sid", self.previous_sid.as_deref().unwrap_or("no")])?;
            }
        }
        self.track_id = None;
        self.file = None;
        self.previous_sid = None;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::{Cell, RefCell};
    const ASS: &str = "[Script Info]\nScriptType: v4.00+\n[Events]\n";
    struct Fake {
        ready: Cell<bool>,
        sid: RefCell<String>,
        path: RefCell<Option<String>>,
        commands: RefCell<Vec<Vec<String>>>,
    }
    impl SubtitleBackend for Fake {
        fn command(&self, args: &[&str]) -> Result<(), String> {
            self.commands
                .borrow_mut()
                .push(args.iter().map(|value| value.to_string()).collect());
            if args[0] == "sub-add" {
                *self.path.borrow_mut() = Some(args[1].into());
            }
            if args[0] == "sub-remove" {
                *self.path.borrow_mut() = None;
            }
            if args[0] == "set" && args[1] == "sid" {
                *self.sid.borrow_mut() = args[2].into();
            }
            Ok(())
        }
        fn selected_subtitle(&self) -> String {
            self.sid.borrow().clone()
        }
        fn track_for_file(&self, path: &str) -> Option<i64> {
            (self.path.borrow().as_deref() == Some(path)).then_some(7)
        }
        fn media_ready(&self) -> bool {
            self.ready.get()
        }
    }
    fn request(revision: u64, content: Option<&str>) -> DanmakuRequest {
        DanmakuRequest {
            session_id: "test".into(),
            revision,
            ass_content: content.map(str::to_string),
            visible: true,
        }
    }
    #[test]
    fn waits_for_media_coalesces_revisions_and_restores_only_owned_track() {
        let backend = Fake {
            ready: Cell::new(false),
            sid: RefCell::new("3".into()),
            path: RefCell::new(None),
            commands: RefCell::new(Vec::new()),
        };
        let mut track = SubtitleTrack::default();
        assert_eq!(
            track.set(request(1, Some(ASS)), &backend).unwrap().state,
            "pending"
        );
        assert!(backend.commands.borrow().is_empty());
        track.set(request(2, Some(ASS)), &backend).unwrap();
        backend.ready.set(true);
        assert_eq!(track.flush(&backend).unwrap().state, "applied");
        let file = backend.path.borrow().clone().unwrap();
        assert!(std::path::Path::new(&file).is_file());
        assert_eq!(backend.selected_subtitle(), "7");
        let calls = backend.commands.borrow().len();
        track.set(request(1, None), &backend).unwrap();
        assert_eq!(backend.commands.borrow().len(), calls);
        assert_eq!(
            track.set(request(3, None), &backend).unwrap().state,
            "cleared"
        );
        assert_eq!(backend.selected_subtitle(), "3");
        assert!(!std::path::Path::new(&file).exists());
    }
    #[test]
    fn rejects_oversized_nul_and_non_ass_payloads() {
        assert!(validate(&request(0, Some("not ass"))).is_err());
        assert!(validate(&request(u64::MAX, Some(ASS))).is_err());
        assert!(validate(&request(1, Some(&format!("{ASS}\0")))).is_err());
        assert!(validate(&request(1, Some(&"x".repeat(MAX_ASS_BYTES + 1)))).is_err());
    }
}
